server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: root                                                    #数据库登陆用户名
    password: 12345                                                   #数据库登陆密码
    url: jdbc:mysql://localhost:3306/test                             #数据库url
    driver-class-name: com.mysql.cj.jdbc.Driver                       #数据库驱动
    druid:
      # Druid连接池的配置
      initial-size: 5                                                 #初始化连接大小
      min-idle: 5                                                     #最小连接池数量
      max-active: 20                                                  #最大连接池数量
      # Druid监控配置信息：StatViewServlet配置
      stat-view-servlet:
        enabled: true                                                 #是否开启内置监控页面，默认值为 false
        url-pattern: '/druid/*'                                       #StatViewServlet 的映射路径，即内置监控页面的访问地址
        reset-enable: true                                            #是否启用重置按钮
        login-username: admin                                         #内置监控页面的登录页用户名 username
        login-password: 12345                                         #内置监控页面的登录页密码 password
