<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>row</name>
   <tag></tag>
   <elementGuidId>03b5ae54-134b-4325-afdc-d3c2eb83a9e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;main&quot;]/div[2]/div[1]/div[1]/div[2]/div/div[3]/table/tbody/tr[${number}]/td[3]/div/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main&quot;]/div[2]/div[1]/div[1]/div[2]/div/div[3]/table/tbody/tr[${number}]/td[3]/div/span/a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;main&quot;]/div[2]/div[1]/div[1]/div[2]/div/div[3]/table/tbody/tr[${number}]/td[3]/div/span/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>number</name>
      <type>Main</type>
      <value>${number}</value>
   </webElementProperties>
</WebElementEntity>
